apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-4rnh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-4rnh
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-4rnh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-4rnh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-4rnh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hgyw-tenant/status-quarkus-io/statusquarkusio-4rnh@sha256:cc936a4baf2321a8425ce2605aba39fbe6a78d3655794e9dbcb0371a617191e9
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
